apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: zookeeper
  namespace: kafka-main
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      name: client
    - port: 2888
      name: peer
    - port: 3888
      name: leader-election
  clusterIP: None
