apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka-brokers
  namespace: kafka-main
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      name: tcp
  type: LoadBalancer