---
- name: Create redis namespace
  kubernetes.core.k8s:
    state: present
    src: /tmp/files/redis-dev/namespace.yml

- name: Install redis Service
  kubernetes.core.k8s:
    state: present
    src: /tmp/files/redis-dev/service.yml

- name: Create redis PersistentVolumeClaim
  kubernetes.core.k8s:
    state: present
    src: /tmp/files/redis-dev/pvc.yml

- name: Install redis Deployment
  kubernetes.core.k8s:
    state: present
    src: /tmp/files/redis-dev/deployment.yml
