---
- name: Ensure redis-dev directory is on the Ansible control node
  when: "'k3s-master' in group_names"
  ansible.builtin.copy:
    src: /home/kali/disk/files
    dest: /tmp
    remote_src: no
    
- name: Create redis namespace
  kubernetes.core.k8s:
    state: present
    src: /tmp/files/redis-dev/namespace.yml

- name: Install redis Service
  kubernetes.core.k8s:
    state: present
    src: /tmp/files/redis-dev/service.yml

- name: Install redis Deployment
  kubernetes.core.k8s:
    state: present
    src: /tmp/files/redis-dev/deployment.yml
