- name: Install Tailscale
  hosts: all
  become: yes
  roles:
  - tailscale

- name: Setup K3s Cluster
  hosts: all
  become: yes
  roles:
  - common

- name: Install K3s on Master Node
  hosts: master
  become: yes
  roles:
  - k3s

- name: Install K3s on Worker Nodes
  hosts: workers
  become: yes
  roles:
  - k3sWorker

- name: Install Monitoring Stack
  hosts: master
  become: yes
  roles:
  - monitoring

- name: Install Kubernetes Dashboard
  hosts: master
  become: yes
  roles:
  - dashboard
