---
- name: Install dependencies
  apt:
    name: [apt-transport-https, ca-certificates, curl, gnupg, lsb-release, openssl]
    state: present
    update_cache: yes

- name: Add HashiCorp APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release | lower }} main"
    state: present

- name: Install Vault
  apt:
    name: vault
    state: latest
    update_cache: yes

- name: Create vault user and directories
  block:
    - name: Create vault user
      user:
        name: vault
        shell: /usr/sbin/nologin

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        owner: vault
        group: vault
        mode: '0750'
      loop:
        - /etc/vault
        - /opt/vault/data-dev

- name: Create Vault configuration file
  copy:
    dest: /etc/vault/config-dev.hcl
    content: |
      storage "file" {
        path = "/opt/vault/data-dev"
      }

      listener "tcp" {
        address     = "0.0.0.0:8201"
        tls-disable = 1
      }

      ui = true
    owner: vault
    group: vault
    mode: '0640'
  notify: Restart Vault

- name: Create systemd service for Vault
  copy:
    dest: /etc/systemd/system/vault-dev.service
    content: |
      [Unit]
      Description=Vault server (dev)
      Requires=network-online.target
      After=network-online.target

      [Service]
      User=vault
      Group=vault
      ExecStart=/usr/bin/vault server -config=/etc/vault/config-dev.hcl
      ExecReload=/bin/kill -HUP $MAINPID
      KillMode=process
      Restart=on-failure
      LimitNOFILE=65536

      [Install]
      WantedBy=multi-user.target
  notify: Restart Vault

- name: Enable and start Vault service
  systemd:
    name: vault-dev
    enabled: yes
    state: started

- name: Enable UFW and allow Vault port
  ufw:
    rule: allow
    port: '8201'
    proto: tcp
  tags: firewall
