apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-main-pvc
  namespace: redis-main
  labels:
    app: redis-main
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
