apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-main
  name: redis-main
  namespace: redis-main
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-main
