- name: Install python3-pip if not installed
  become: true
  apt:
    name: python3-pip
    state: present

- name: Install python3-kubernetes via apt
  become: true
  apt:
    name: python3-kubernetes
    state: present

- name: Install Helm (if not already installed)
  shell: |
    curl -fsSL https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz -o /tmp/helm.tar.gz
    tar -zxvf /tmp/helm.tar.gz -C /tmp
    mv /tmp/linux-amd64/helm /usr/local/bin/helm
  become: true
  when: ansible_facts.packages['helm'] is not defined or ansible_facts.packages['helm'][0].state != 'installed'

- name: Ensure .kube directory exists
  ansible.builtin.file:
    path: "/root/.kube"
    state: directory
    mode: '0700'
  become: true

- name: Copy K3s Kubeconfig to local machine
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /root/.kube/config
    remote_src: yes
    force: yes
  delegate_to: master
  become: true

- name: Create Prometheus Namespace
  kubernetes.core.k8s:
    state: present
    name: prometheus
    api_version: v1
    kind: Namespace
  become: true
  environment:
      KUBECONFIG: /root/.kube/config

- name: Create Grafana Namespace
  kubernetes.core.k8s:
    state: present
    name: grafana
    api_version: v1
    kind: Namespace
  become: true
  environment:
      KUBECONFIG: /root/.kube/config

- name: Ensure Helm is installed
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  become: true

- name: Add Helm Repositories
  shell: |
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    helm repo add grafana https://grafana.github.io/helm-charts
    helm repo update
  become: true

- name: Install or Upgrade Prometheus
  shell: helm upgrade --install prometheus prometheus-community/kube-prometheus-stack --namespace prometheus
  become: true
  environment:
      KUBECONFIG: /root/.kube/config

- name: Install Grafana
  shell: helm upgrade --install grafana grafana/grafana --namespace grafana
  become: true
  environment:
      KUBECONFIG: /root/.kube/config
