---
- name: Ensure auditd service is started and enabled
  service:
    name: auditd
    state: started
    enabled: yes

- name: "Configure audit rules"
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    line: '-w /usr/bin/sudo -p x -k sudo'
    create: yes

- name: Ensure auditd is restarted to apply new rules
  service:
    name: auditd
    state: restarted

- name: Configure audit rules
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    line: "{{ item }}"
    create: yes
  loop:
    - '-w /usr/bin/sudo -p x -k sudo'
    - '-w /usr/bin/passwd -p x -k passwd_change'
    - '-w /etc/ssh/sshd_config -p wa -k ssh_config_changes'

- name: Ensure auditd is restarted to apply new rules
  service:
    name: auditd
    state: restarted
