---
- name: Download Tailscale GPG Key
  ansible.builtin.apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
    state: present

- name: Add Tailscale repository
  ansible.builtin.apt_repository:
    repo: "deb https://pkgs.tailscale.com/stable/ubuntu jammy main"
    filename: tailscale
    state: present

- name: Update package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Tailscale
  ansible.builtin.apt:
    name: tailscale
    state: present

- name: Start Tailscale service
  service:
    name: tailscaled
    state: started
    enabled: yes

- name: Connect to Tailscale network using the provided auth token
  command: tailscale up --authkey={{ tailscale_auth_key }}
  environment:
    TS_KEY: "{{ tailscale_auth_key }}"
  register: tailscale_up_result
  failed_when: "'Error' in tailscale_up_result.stderr"

- name: Check Tailscale status
  command: tailscale status
  register: tailscale_status
  changed_when: false

- name: Show Tailscale status
  debug:
    msg: "Tailscale status: {{ tailscale_status.stdout }}"

- name: Get Tailscale IP
  shell: tailscale ip -4
  register: tailscale_ip
  changed_when: false

- name: Display Tailscale IP
  debug:
    msg: "Tailscale IP of this node is {{ tailscale_ip.stdout }}"
