---
- name: Enable UFW (Uncomplicated Firewall)
  ufw:
    state: enabled
    policy: deny
    logging: on

- name: Allow K3s traffic from specified networks
  ufw:
    rule: allow
    from_ip: "{{ item }}"
    to_port: 6443
    proto: tcp
  loop: "{{ [ '192.168.0.0/24', '100.0.0.0/8' ] }}"
  loop_control:
    label: "Allowing from {{ item }}"
