---
- name: Get current hostname
  command: hostname -f
  register: current_hostname_output
  changed_when: false

- name: Set hostname using hostnamectl
  command: "sudo hostnamectl set-hostname {{ inventory_hostname }}"
  when: current_hostname_output.stdout != inventory_hostname
  register: hostname_change_result
  failed_when: hostname_change_result.rc != 0

- name: Display hostname change result
  debug:
    var: hostname_change_result

- name: Update all apt repositories and installed packages
  block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
      register: update_result
      failed_when: "'dpkg was interrupted' in update_result.msg"
  rescue:
    - name: Attempt to fix interrupted dpkg configuration
      ansible.builtin.command:
        cmd: "dpkg --configure -a"
      register: dpkg_reconfigure
      changed_when: dpkg_reconfigure.rc != 0
      failed_when: dpkg_reconfigure.rc != 0
    - name: Retry apt update and upgrade after dpkg fix
      ansible.builtin.apt:
        update_cache: yes
      when: "'dpkg was interrupted' in update_result.msg and dpkg_reconfigure.rc == 0"
    - name: Retry apt upgrade after dpkg fix
      ansible.builtin.apt:
        upgrade: dist
      register: update_result
      when: "'dpkg was interrupted' in update_result.msg and dpkg_reconfigure.rc == 0"
      until: update_result is success
      retries: 3
      delay: 5

- name: Install essential packages
  ansible.builtin.apt:
    name:
      - ufw
      - fail2ban
      - htop
      - vim
      - curl
      - net-tools
      - wget
      - iputils-ping
      - apt-transport-https
      - gnupg
      - lsb-release
      - software-properties-common
      - jq
      - unzip
      - dnsutils
      - ca-certificates
      - socat
      - iptables
      - conntrack
      - logrotate
    state: present
    update_cache: yes
