---
- name: Get current hostname
  command: hostname -f
  register: current_hostname_output
  changed_when: false

- name: Set hostname using hostnamectl
  command: "sudo hostnamectl set-hostname {{ inventory_hostname }}"
  when: current_hostname_output.stdout != inventory_hostname
  register: hostname_change_result
  failed_when: hostname_change_result.rc != 0

- name: Display hostname change result
  debug:
    var: hostname_change_result

- name: Update all apt repositories and installed packages
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600

- name: Install essential packages
  apt:
    name:
      - ufw
      - fail2ban
      - htop
      - vim
      - curl
      - net-tools
      - wget
      - iputils-ping
      - apt-transport-https
      - gnupg
      - lsb-release
      - software-properties-common
      - jq
      - unzip
      - dnsutils
      - ca-certificates
      - socat
      - iptables
      - conntrack
      - logrotate
    state: present
    update_cache: yes
