- name: Update and install dependencies
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - apt-transport-https
    - gnupg
    - software-properties-common
    - jq
    - unzip
    - dnsutils
    - ca-certificates
    - net-tools
    - socat
    - iptables
    - conntrack
