---
- name: Deploy PostgreSQL Namespace
  kubernetes.core.k8s:
    state: present
    name: postgresql-selecro-dev
    api_version: v1
    kind: Namespace
  become: true

- name: Create directory for PostgreSQL data storage
  file:
    path: /mnt/data/postgresql-selecro-dev
    state: directory
    mode: '0755'
  become: true

- name: Create PostgreSQL Persistent Volume
  kubernetes.core.k8s:
    state: present
    namespace: postgresql-selecro-dev
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: postgresql-selecro-dev-pv
      spec:
        capacity:
          storage: 1Gi
        accessModes:
          - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        hostPath:
          path: /mnt/data/postgresql-selecro-dev
        storageClassName: manual
    force: true
  become: true

- name: Deploy PostgreSQL StatefulSet
  kubernetes.core.k8s:
    state: present
    namespace: postgresql-selecro-dev
    definition:
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: postgresql
      spec:
        serviceName: postgresql
        replicas: 1
        selector:
          matchLabels:
            app: postgresql-selecro-dev
        template:
          metadata:
            labels:
              app: postgresql-selecro-dev
          spec:
            containers:
              - name: postgresql-selecro-dev
                image: postgres:13
                env:
                  - name: POSTGRES_USER
                    valueFrom:
                      secretKeyRef:
                        name: postgresql-selecro-dev-secret
                        key: POSTGRES_USER
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: postgresql-selecro-dev-secret
                        key: POSTGRES_PASSWORD
                  - name: POSTGRES_DB
                    valueFrom:
                      secretKeyRef:
                        name: postgresql-selecro-dev-secret
                        key: POSTGRES_DB
                ports:
                  - containerPort: 5432
                volumeMounts:
                  - name: postgresql-selecro-dev-data
                    mountPath: /var/lib/postgresql/data
        volumeClaimTemplates:
          - metadata:
              name: postgresql-selecro-dev-data
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
              storageClassName: manual
  become: true

- name: Create PostgreSQL Secrets
  kubernetes.core.k8s:
    state: present
    namespace: postgresql-selecro-dev
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: postgresql-selecro-dev-secret
      type: Opaque
      data:
        POSTGRES_USER: "{{ postgres_user | b64encode }}"
        POSTGRES_PASSWORD: "{{ postgres_password | b64encode }}"
        POSTGRES_DB: "{{ postgres_db | b64encode }}"
  become: true

- name: Expose PostgreSQL with a service
  kubernetes.core.k8s:
    state: present
    namespace: postgresql-selecro-dev
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: postgresql-selecro-dev
      spec:
        selector:
          app: postgresql-selecro-dev
        ports:
          - port: 5432
            targetPort: 5432
        clusterIP: None
  become: true