apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-dev-pvc
  namespace: redis-dev
  labels:
    app: redis-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
