apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-dev
  name: redis-dev
  namespace: redis-dev
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-dev
