---
- name: Basic Setup for Ubuntu Servers
  hosts: k3s-cluster
  become: yes
  roles:
    - basic_setup
    - fail2ban
    - ssh
    - auditd
    - logrotate_config
    - unattended_upgrades
    - ids
    - firewall
    - tailscale
    - k3s
